name: "go_web_scaffold"
mode: "dev"
version: "v1.0"
host: "127.0.0.1"
port: 8081

log:
  level: "debug"
  filename: "go_web_scaffold.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3308
  user: "root"
  password: "rootroot"
  db_name: "gomysql_demo"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100